{
  "hash": "d432c7914d2758e2412aa884aa70fa21",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"dsOMOP — Exercises (Solutions)\"\nformat:\n  html:\n    code-copy: true\nexecute:\n  warning: false\n  message: false\n  error: true\n---\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(DSI); library(DSOpal); library(dsBaseClient); library(dsOMOPClient)\n\nbuilder <- DSI::newDSLoginBuilder()\nfor (s in c(\"nairobi\", \"douala\", \"dakar\"))\n  builder$append(server = s, url = paste0(\"https://\", s, \".datashield.live\"),\n                 user = \"ethiopia\", password = \"P@ssw0rd\", profile = \"omop\")\nconns <- DSI::datashield.login(logins = builder$build())\nds.omop.connect(resource = \"omop_demo.mimic\", symbol = \"omop\", conns = conns)\n```\n:::\n\n\n# Exercise 1 — A new numeric variable\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshow_tbl(ds.omop.column.stats(\"measurement\", \"value_as_number\", concept_id = 21492239,\n                              scope = \"pooled\", symbol = \"omop\", conns = conns)$pooled)\n```\n\n::: {.cell-output-display}\n\n\n<table class=\"kable_wrapper\">\n<tbody>\n  <tr>\n   <td> \n\n|    x|\n|----:|\n| 8365|\n\n </td>\n   <td> \n\n|        x|\n|--------:|\n| 115.1706|\n\n </td>\n   <td> \n\n|        x|\n|--------:|\n| 21.79551|\n\n </td>\n  </tr>\n</tbody>\n</table>\n\n\n:::\n\n```{.r .cell-code}\nh <- ds.omop.value.histogram(\"measurement\", value_col = \"value_as_number\",\n                             concept_id = 21492239, symbol = \"omop\", conns = conns)\nbins <- do.call(rbind, h$per_site)\nbins <- subset(bins, !is.na(count))\nbins <- aggregate(count ~ bin_start, data = bins, FUN = sum)\nbins <- bins[order(bins$bin_start), ]\nbarplot(bins$count, names.arg = round(bins$bin_start), las = 2, col = \"#4C72B0\", border = NA,\n        xlab = \"Systolic BP (mmHg)\", ylab = \"records\", main = \"Systolic blood pressure\")\n```\n\n::: {.cell-output-display}\n![](omop_exercises_solution_files/figure-html/e1-1.png){width=672}\n:::\n:::\n\n\n> **Answer.** Systolic blood pressure is roughly **symmetric** (mean ≈ median, ~115–120 mmHg), with a **wider spread** than heart rate (sd ≈ 22 vs ≈ 19). A broad-but-symmetric distribution is typical of blood pressure.\n\n# Exercise 2 — A new categorical variable\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrh <- ds.omop.value.counts(\"observation\", \"value_as_concept_id\", concept_id = 40766231,\n                           symbol = \"omop\", conns = conns)\nshow_tbl(rh$per_site$nairobi)\n```\n\n::: {.cell-output-display}\n\n\n|value    |  n| n_persons|concept_name  |\n|:--------|--:|---------:|:-------------|\n|45881671 | 40|        10|Never married |\n|45883711 | 25|         5|Widowed       |\n|45876756 | 25|        10|Married       |\n|45883375 |  0|         0|Divorced      |\n\n\n:::\n:::\n\n\n> **Answer.** The most common status is **Never married**, followed by **Married** and **Widowed**. Some categories are suppressed on this ~100-patient cohort (small-cell control).\n\n# Exercise 3 — Find a concept yourself\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshow_tbl(ds.omop.concept.search(\"hyperlipidemia\", domain = \"Condition\",\n                                symbol = \"omop\", conns = conns))\n```\n\n::: {.cell-output-display}\n\n\n<table class=\"kable_wrapper\">\n<tbody>\n  <tr>\n   <td> \n\n<table class=\"kable_wrapper\">\n<tbody>\n  <tr>\n   <td> \n\n| concept_id|concept_name   |domain_id |vocabulary_id |standard_concept |concept_class_id |concept_code |valid_start_date |valid_end_date |invalid_reason |\n|----------:|:--------------|:---------|:-------------|:----------------|:----------------|:------------|:----------------|:--------------|:--------------|\n|     432867|Hyperlipidemia |Condition |SNOMED        |S                |Disorder         |55822004     |1970-01-01       |2099-12-31     |NA             |\n\n </td>\n   <td> \n\n| concept_id|concept_name   |domain_id |vocabulary_id |standard_concept |concept_class_id |concept_code |valid_start_date |valid_end_date |invalid_reason |\n|----------:|:--------------|:---------|:-------------|:----------------|:----------------|:------------|:----------------|:--------------|:--------------|\n|     432867|Hyperlipidemia |Condition |SNOMED        |S                |Disorder         |55822004     |1970-01-01       |2099-12-31     |NA             |\n\n </td>\n   <td> \n\n| concept_id|concept_name   |domain_id |vocabulary_id |standard_concept |concept_class_id |concept_code |valid_start_date |valid_end_date |invalid_reason |\n|----------:|:--------------|:---------|:-------------|:----------------|:----------------|:------------|:----------------|:--------------|:--------------|\n|     432867|Hyperlipidemia |Condition |SNOMED        |S                |Disorder         |55822004     |1970-01-01       |2099-12-31     |NA             |\n\n </td>\n  </tr>\n</tbody>\n</table>\n\n </td>\n   <td> \n\n| concept_id|concept_name   |domain_id |vocabulary_id |standard_concept |concept_class_id |concept_code |valid_start_date |valid_end_date |invalid_reason |\n|----------:|:--------------|:---------|:-------------|:----------------|:----------------|:------------|:----------------|:--------------|:--------------|\n|     432867|Hyperlipidemia |Condition |SNOMED        |S                |Disorder         |55822004     |1970-01-01       |2099-12-31     |NA             |\n\n </td>\n   <td> \n\n<table class=\"kable_wrapper\">\n<tbody>\n  <tr>\n   <td> \n\n|x                                                                                                                           |\n|:---------------------------------------------------------------------------------------------------------------------------|\n|ds.omop.concept.search(pattern = \"hyperlipidemia\", domain = \"Condition\", standard_only = TRUE, limit = 50, symbol = \"omop\") |\n\n </td>\n   <td> \n\n|x                   |\n|:-------------------|\n|2026-06-16 07:35:16 |\n\n </td>\n   <td> \n\n|x       |\n|:-------|\n|nairobi |\n|douala  |\n|dakar   |\n\n </td>\n   <td> \n\n|x      |\n|:------|\n|pooled |\n\n </td>\n   <td> \n\n|x      |\n|:------|\n|strict |\n\n </td>\n   <td> \n\n|x  |\n|:--|\n\n </td>\n  </tr>\n</tbody>\n</table>\n\n </td>\n  </tr>\n</tbody>\n</table>\n\n\n:::\n:::\n\n\n> **Answer.** Hyperlipidemia is **`concept_id = 432867`**, present in about **45** of the ~100 patients — one of the most common conditions in this ICU cohort.\n\n# Exercise 4 — Build your own recipe\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrec <- omop_recipe(\n  variables = list(\n    omop_variable(table = \"person\", column = \"gender_concept_id\", format = \"sex_mf\", name = \"sex\"),\n    omop_variable_age(name = \"age\"),\n    omop_variable(table = \"measurement\", concept_id = 21492239, format = \"mean\", name = \"systolic_bp\"),\n    omop_variable(table = \"condition_occurrence\", concept_id = 432867, format = \"binary\", name = \"hyperlipidemia\")),\n  outputs = omop_output(name = \"study\", type = \"wide\"))\n\nrecipe_execute(rec, out = c(study = \"D\"), symbol = \"omop\", conns = conns)\nds.colnames(\"D\", datasources = conns)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> $nairobi\n#> [1] \"person_id\"      \"systolic_bp\"    \"hyperlipidemia\" \"sex\"           \n#> [5] \"age\"           \n#> \n#> $douala\n#> [1] \"person_id\"      \"systolic_bp\"    \"hyperlipidemia\" \"sex\"           \n#> [5] \"age\"           \n#> \n#> $dakar\n#> [1] \"person_id\"      \"systolic_bp\"    \"hyperlipidemia\" \"sex\"           \n#> [5] \"age\"\n```\n\n\n:::\n\n```{.r .cell-code}\nds.dim(\"D\", datasources = conns)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> $`dimensions of D in nairobi`\n#> [1] 35  5\n#> \n#> $`dimensions of D in douala`\n#> [1] 25  5\n#> \n#> $`dimensions of D in dakar`\n#> [1] 40  5\n#> \n#> $`dimensions of D in combined studies`\n#> [1] 100   5\n```\n\n\n:::\n\n```{.r .cell-code}\nds.summary(\"D$systolic_bp\", datasources = conns)[[1]][[\"quantiles & mean\"]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>        5%       10%       25%       50%       75%       90%       95%      Mean \n#>  99.72277 104.13354 112.25500 120.19672 128.68355 133.01607 142.95000 120.33293\n```\n\n\n:::\n:::\n\n\n> **Answer.** `D` has one row per patient with `sex`, `age`, `systolic_bp`, `hyperlipidemia` (plus `person_id`); ~100 patients combined, mean systolic BP near 120 mmHg.\n\n# Exercise 5 — Filter at extraction\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrec_old <- omop_recipe(\n  variables = list(\n    omop_variable(table = \"person\", column = \"gender_concept_id\", format = \"sex_mf\", name = \"sex\"),\n    omop_variable_age(name = \"age\"),\n    omop_variable(table = \"condition_occurrence\", concept_id = 432867, format = \"binary\", name = \"hyperlipidemia\")),\n  filters  = list(older = omop_filter_age(min = 60)),\n  outputs  = omop_output(name = \"study\", type = \"wide\"))\nrecipe_execute(rec_old, out = c(study = \"D_old\"), symbol = \"omop\", conns = conns)\n\nds.dim(\"D_old\", datasources = conns)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> $`dimensions of D_old in nairobi`\n#> [1] 23  4\n#> \n#> $`dimensions of D_old in douala`\n#> [1] 13  4\n#> \n#> $`dimensions of D_old in dakar`\n#> [1] 31  4\n#> \n#> $`dimensions of D_old in combined studies`\n#> [1] 67  4\n```\n\n\n:::\n\n```{.r .cell-code}\nds.summary(\"D_old$age\", datasources = conns)[[1]][[\"quantiles & mean\"]]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>       5%      10%      25%      50%      75%      90%      95%     Mean \n#> 60.00000 60.20000 65.00000 74.00000 81.50000 89.60000 92.70000 74.56522\n```\n\n\n:::\n:::\n\n\n> **Answer.** The filter is applied **during** extraction, so the servers only build patients aged 60+. The cohort shrinks and the minimum age is now 60.\n\n# Exercise 6 — A model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrec_h <- omop_recipe(\n  variables = list(\n    omop_variable(table = \"person\", column = \"gender_concept_id\", format = \"sex_mf\", name = \"sex\"),\n    omop_variable_age(name = \"age\"),\n    omop_variable(table = \"condition_occurrence\", concept_id = 432867, format = \"binary\", name = \"hyperlipidemia\")),\n  outputs = omop_output(name = \"study\", type = \"wide\"))\nrecipe_execute(rec_h, out = c(study = \"H\"), symbol = \"omop\", conns = conns)\nfit <- ds.glm(\"H$hyperlipidemia ~ H$age + H$sex\", family = \"binomial\", datasources = conns)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nco <- fit$coefficients\nshow_tbl(data.frame(\n  term = rownames(co), OR = round(co[, \"P_OR\"], 2),\n  CI_low = round(co[, \"low0.95CI.P_OR\"], 2), CI_high = round(co[, \"high0.95CI.P_OR\"], 2),\n  p_value = signif(co[, \"p-value\"], 3), row.names = NULL))\n```\n\n::: {.cell-output-display}\n\n\n|term        |   OR| CI_low| CI_high|  p_value|\n|:-----------|----:|------:|-------:|--------:|\n|(Intercept) | 0.01|   0.00|    0.08| 6.98e-05|\n|H$age       | 1.07|   1.04|    1.11| 4.43e-05|\n|H$sexM      | 0.99|   0.40|    2.42| 9.75e-01|\n\n\n:::\n:::\n\n\n> **Answer.** **age** is a strong, significant predictor of hyperlipidemia (odds rise with age, p < 0.001) — clinically sensible, since cholesterol problems accumulate over a lifetime. **sex** is not significant. A clean, honest single-predictor result.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDSI::datashield.logout(conns)\n```\n:::\n\n",
    "supporting": [
      "omop_exercises_solution_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}