{
  "hash": "06c94ae93c6dd4b3a02e7aae5ba4bed3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"GiBleed — Exercises (Solutions)\"\nsubtitle: \"One worked path through each exercise, with real federated output\"\nformat: html\nexecute:\n  warning: false\n  message: false\n  error: true\n---\n\n<a href=\"#\" onclick=\"event.preventDefault(); fetch('https://raw.githubusercontent.com/isglobal-brge/workshop_DSWB/main/gibleed_solution.R').then(response => response.blob()).then(blob => { const url = window.URL.createObjectURL(blob); const a = document.createElement('a'); a.style.display = 'none'; a.href = url; a.download = 'gibleed_solution.R'; document.body.appendChild(a); a.click(); window.URL.revokeObjectURL(url); }); return false;\" class=\"btn btn-primary btn-sm\">\n<i class=\"bi bi-download\"></i> Download the solutions (.R)\n</a>\n<a href=\"gibleed-exercises.html\" class=\"btn btn-outline-secondary btn-sm\">\n<i class=\"bi bi-arrow-left\"></i> Back to the exercises\n</a>\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(DSI); library(DSOpal); library(dsBaseClient); library(dsOMOPClient)\n\nbuilder <- DSI::newDSLoginBuilder()\nbuilder$append(server = \"nairobi\", url = \"https://nairobi.datashield.live\",\n               user = \"ethiopia\", password = \"P@ssw0rd\", profile = \"omop\")\nbuilder$append(server = \"douala\",  url = \"https://douala.datashield.live\",\n               user = \"ethiopia\", password = \"P@ssw0rd\", profile = \"omop\")\nbuilder$append(server = \"dakar\",   url = \"https://dakar.datashield.live\",\n               user = \"ethiopia\", password = \"P@ssw0rd\", profile = \"omop\")\nconns <- DSI::datashield.login(logins = builder$build())\nds.omop.connect(resource = \"omop_demo.gibleed\", symbol = \"omop\", conns = conns)\n```\n:::\n\n\nThese are *one* valid path; your concepts/variables may differ. (GiBleed has no numeric values, so everything is a boolean flag; age is anchored to 2019.)\n\n# Exercise 1 — Find a medication\n\n\n::: {.cell}\n\n```{.r .cell-code}\nds.omop.concept.search(\"celecoxib\", domain = \"Drug\",\n                       symbol = \"omop\", conns = conns)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> $nairobi\n#>   concept_id                             concept_name domain_id vocabulary_id standard_concept concept_class_id concept_code valid_start_date valid_end_date invalid_reason\n#> 1    1118088 celecoxib 200 MG Oral Capsule [Celebrex]      Drug        RxNorm                S     Branded Drug       213469       1970-01-01     2099-12-31           <NA>\n#> 2    1118084                                celecoxib      Drug        RxNorm                S       Ingredient       140587       1970-01-01     2099-12-31           <NA>\n#> \n#> $douala\n#>   concept_id                             concept_name domain_id vocabulary_id standard_concept concept_class_id concept_code valid_start_date valid_end_date invalid_reason\n#> 1    1118088 celecoxib 200 MG Oral Capsule [Celebrex]      Drug        RxNorm                S     Branded Drug       213469       1970-01-01     2099-12-31           <NA>\n#> 2    1118084                                celecoxib      Drug        RxNorm                S       Ingredient       140587       1970-01-01     2099-12-31           <NA>\n#> \n#> $dakar\n#>   concept_id                             concept_name domain_id vocabulary_id standard_concept concept_class_id concept_code valid_start_date valid_end_date invalid_reason\n#> 1    1118088 celecoxib 200 MG Oral Capsule [Celebrex]      Drug        RxNorm                S     Branded Drug       213469       1970-01-01     2099-12-31           <NA>\n#> 2    1118084                                celecoxib      Drug        RxNorm                S       Ingredient       140587       1970-01-01     2099-12-31           <NA>\n#> \n#> $pooled\n#>   concept_id                             concept_name domain_id vocabulary_id standard_concept concept_class_id concept_code valid_start_date valid_end_date invalid_reason\n#> 1    1118088 celecoxib 200 MG Oral Capsule [Celebrex]      Drug        RxNorm                S     Branded Drug       213469       1970-01-01     2099-12-31           <NA>\n#> 2    1118084                                celecoxib      Drug        RxNorm                S       Ingredient       140587       1970-01-01     2099-12-31           <NA>\n```\n\n\n:::\n\n```{.r .cell-code}\nds.omop.concept.prevalence(\"drug_exposure\", metric = \"persons\", top_n = 12,\n                           scope = \"pooled\", symbol = \"omop\", conns = conns)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#> $nairobi\n#>    concept_id                                                                                                      concept_name n_persons n_records\n#> 1    40213227                                        tetanus and diphtheria toxoids, adsorbed, preservative free, for adult use       875      2470\n#> 2     1127433                                                                                  Acetaminophen 325 MG Oral Tablet       850      3070\n#> 3    40213160                                                                                   poliovirus vaccine, inactivated       715      2700\n#> 4     1713671                                                               Amoxicillin 250 MG / Clavulanate 125 MG Oral Tablet       655      1250\n#> 5    19059056                                                                                         Aspirin 81 MG Oral Tablet       615      1410\n#> 6     1118084                                                                                                         celecoxib       595       595\n#> 7    40213296                                                                                 hepatitis A vaccine, adult dosage       590      1100\n#> 8    40213306                                                                                 hepatitis B vaccine, adult dosage       530       645\n#> 9     1127078                                                                                  Acetaminophen 160 MG Oral Tablet       470       695\n#> 10   19078461                                                                                      Ibuprofen 200 MG Oral Tablet       445       590\n#> 11   40229134 Acetaminophen 21.7 MG/ML / Dextromethorphan Hydrobromide 1 MG/ML / doxylamine succinate 0.417 MG/ML Oral Solution       425       600\n#> 12   19133873                                                                         Penicillin V Potassium 250 MG Oral Tablet       425       565\n#> \n#> $douala\n#>    concept_id                                                                                                      concept_name n_persons n_records\n#> 1    40213227                                        tetanus and diphtheria toxoids, adsorbed, preservative free, for adult use       870      2425\n#> 2     1127433                                                                                  Acetaminophen 325 MG Oral Tablet       845      2985\n#> 3    40213160                                                                                   poliovirus vaccine, inactivated       700      2620\n#> 4     1713671                                                               Amoxicillin 250 MG / Clavulanate 125 MG Oral Tablet       665      1260\n#> 5    19059056                                                                                         Aspirin 81 MG Oral Tablet       630      1345\n#> 6     1118084                                                                                                         celecoxib       615       615\n#> 7    40213296                                                                                 hepatitis A vaccine, adult dosage       565      1050\n#> 8    40213306                                                                                 hepatitis B vaccine, adult dosage       515       635\n#> 9     1127078                                                                                  Acetaminophen 160 MG Oral Tablet       480       740\n#> 10   40229134 Acetaminophen 21.7 MG/ML / Dextromethorphan Hydrobromide 1 MG/ML / doxylamine succinate 0.417 MG/ML Oral Solution       455       645\n#> 11   19078461                                                                                      Ibuprofen 200 MG Oral Tablet       380       540\n#> 12   19133873                                                                         Penicillin V Potassium 250 MG Oral Tablet       380       530\n#> \n#> $dakar\n#>    concept_id                                                                                                      concept_name n_persons n_records\n#> 1    40213227                                        tetanus and diphtheria toxoids, adsorbed, preservative free, for adult use       910      2525\n#> 2     1127433                                                                                  Acetaminophen 325 MG Oral Tablet       880      3305\n#> 3    40213160                                                                                   poliovirus vaccine, inactivated       720      2655\n#> 4     1713671                                                               Amoxicillin 250 MG / Clavulanate 125 MG Oral Tablet       695      1335\n#> 5    19059056                                                                                         Aspirin 81 MG Oral Tablet       675      1615\n#> 6     1118084                                                                                                         celecoxib       630       630\n#> 7    40213296                                                                                 hepatitis A vaccine, adult dosage       575      1055\n#> 8    40213306                                                                                 hepatitis B vaccine, adult dosage       510       630\n#> 9    40229134 Acetaminophen 21.7 MG/ML / Dextromethorphan Hydrobromide 1 MG/ML / doxylamine succinate 0.417 MG/ML Oral Solution       505       745\n#> 10    1127078                                                                                  Acetaminophen 160 MG Oral Tablet       475       715\n#> 11   19133873                                                                         Penicillin V Potassium 250 MG Oral Tablet       465       620\n#> 12   19078461                                                                                      Ibuprofen 200 MG Oral Tablet       445       630\n#> \n#> $pooled\n#>    concept_id n_persons                                                                                                      concept_name\n#> 1    40213227      2655                                        tetanus and diphtheria toxoids, adsorbed, preservative free, for adult use\n#> 2     1127433      2575                                                                                  Acetaminophen 325 MG Oral Tablet\n#> 3    40213160      2135                                                                                   poliovirus vaccine, inactivated\n#> 4     1713671      2015                                                               Amoxicillin 250 MG / Clavulanate 125 MG Oral Tablet\n#> 5    19059056      1920                                                                                         Aspirin 81 MG Oral Tablet\n#> 6     1118084      1840                                                                                                         celecoxib\n#> 7    40213296      1730                                                                                 hepatitis A vaccine, adult dosage\n#> 8    40213306      1555                                                                                 hepatitis B vaccine, adult dosage\n#> 9     1127078      1425                                                                                  Acetaminophen 160 MG Oral Tablet\n#> 10   40229134      1385 Acetaminophen 21.7 MG/ML / Dextromethorphan Hydrobromide 1 MG/ML / doxylamine succinate 0.417 MG/ML Oral Solution\n#> 11   19078461      1270                                                                                      Ibuprofen 200 MG Oral Tablet\n#> 12   19133873      1270                                                                         Penicillin V Potassium 250 MG Oral Tablet\n```\n\n\n:::\n:::\n\n\n> Celecoxib (an NSAID) is concept **1118084**, taken by ~1,840 patients.\n\n# Exercise 2 — Does that drug relate to GI bleeding?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nds.omop.concept.search(\"gastrointestinal hemorrhage\", domain = \"Condition\",\n                       symbol = \"omop\", conns = conns)\n\nrec <- omop_recipe(\n  variables = list(\n    omop_variable(table = \"person\", column = \"gender_concept_id\", format = \"sex_mf\", name = \"sex\"),\n    omop_variable_age(name = \"age\", year = 2019),\n    omop_variable(table = \"condition_occurrence\", concept_id = 192671, format = \"binary\", name = \"gi_bleed\"),\n    omop_variable(table = \"drug_exposure\", concept_id = 1118084, format = \"binary\", name = \"celecoxib\")\n  ),\n  output = omop_output(name = \"study\", type = \"wide\"))\nrecipe_execute(rec, out = c(study = \"M\"), symbol = \"omop\", conns = conns)\n\nfit <- ds.glm(formula = \"M$gi_bleed ~ M$age + M$sex + M$celecoxib\",\n              family = \"binomial\", datasources = conns)\nfit$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                Estimate  Std. Error    z-value      p-value low0.95CI.LP high0.95CI.LP      P_OR low0.95CI.P_OR high0.95CI.P_OR\n#> (Intercept) -1.88391772 0.220939678 -8.5268420 1.503971e-17 -2.316951532  -1.450883909 0.1319395     0.08972874       0.1898656\n#> M$age        0.00175471 0.003102217  0.5656310 5.716446e-01 -0.004325523   0.007834943 1.0017563     0.99568382       1.0078657\n#> M$sexM       0.01777466 0.100978142  0.1760248 8.602744e-01 -0.180138860   0.215688183 1.0179336     0.83515423       1.2407154\n#> M$celecoxib  0.33459251 0.113757828  2.9412702 3.268693e-03  0.111631264   0.557553755 1.3973709     1.11810050       1.7463952\n```\n\n\n:::\n:::\n\n\n> GI haemorrhage is concept **192671**. Celecoxib is a **significant** predictor: its `P_OR` is above 1 (~1.4, `p` ≈ 0.003) — an NSAID raising GI-bleed odds. Age and sex are not significant.\n\n# Exercise 3 — Does age predict a fracture?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nds.omop.concept.search(\"fracture of forearm\", domain = \"Condition\",\n                       symbol = \"omop\", conns = conns)\n\nrec_fx <- omop_recipe(\n  variables = list(\n    omop_variable(table = \"person\", column = \"gender_concept_id\", format = \"sex_mf\", name = \"sex\"),\n    omop_variable_age(name = \"age\", year = 2019),\n    omop_variable(table = \"condition_occurrence\", concept_id = 4278672, format = \"binary\", name = \"fx_forearm\")\n  ),\n  output = omop_output(name = \"study\", type = \"wide\"))\nrecipe_execute(rec_fx, out = c(study = \"FX\"), symbol = \"omop\", conns = conns)\n\nfit_fx <- ds.glm(formula = \"FX$fx_forearm ~ FX$age + FX$sex\", family = \"binomial\", datasources = conns)\nfit_fx$coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n#>                Estimate  Std. Error     z-value      p-value low0.95CI.LP high0.95CI.LP      P_OR low0.95CI.P_OR high0.95CI.P_OR\n#> (Intercept) -2.69070113 0.198348029 -13.5655551 6.409258e-42  -3.07945612   -2.30194613 0.0635243     0.04396267      0.09096191\n#> FX$age       0.01952019 0.002877867   6.7828678 1.178135e-11   0.01387968    0.02516071 1.0197120     1.01397644      1.02547991\n#> FX$sexM      0.03280358 0.099295238   0.3303641 7.411248e-01  -0.16181151    0.22741867 1.0333476     0.85060152      1.25535534\n```\n\n\n:::\n:::\n\n\n> Forearm fracture is concept **4278672**. Now **age** is the significant predictor (`P_OR` slightly above 1 — older patients fracture more), while sex is not. The contrast with Exercise 2 is the point: which predictor matters depends on the outcome.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDSI::datashield.logout(conns)\n```\n:::\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}