<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Federated OMOP analysis with dsOMOP – DataSHIELD DSWB Workshop</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./images/isglobal_logo.jpg" rel="icon" type="image/jpeg">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-afdc90b34ebced266e103efb07108d1c.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-2bedaaaaae570aa036a624c60b2fba77.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&amp;display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">


<link rel="stylesheet" href="styles.css">
<link rel="stylesheet" href="navbar-fix.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> <i class="bi bi-house-fill" role="img">
</i>
<span class="menu-text">Home</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./getting-started.html"> <i class="bi bi-play-circle-fill" role="img">
</i>
<span class="menu-text">Getting Started</span></a>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-workshops" role="link" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-mortarboard-fill" role="img">
</i>
 <span class="menu-text">Workshops</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-workshops">
        <li>
    <a class="dropdown-item" href="./datashield-presentation.html"><i class="bi bi-file-earmark-slides" role="img">
</i>
 <span class="dropdown-text">DataSHIELD Presentation</span></a>
  </li>
        <li>
    <a class="dropdown-item" href="./DataSHIELD_workshop_DSWB_tables.html"><i class="bi bi-table" role="img">
</i>
 <span class="dropdown-text">DataSHIELD (Tables)</span></a>
  </li>
        <li>
    <a class="dropdown-item" href="./DataSHIELD_workshop_DSWB_resources.html"><i class="bi bi-link-45deg" role="img">
</i>
 <span class="dropdown-text">DataSHIELD (Resources)</span></a>
  </li>
        <li>
    <a class="dropdown-item" href="./omop-presentation.html"><i class="bi bi-file-earmark-slides" role="img">
</i>
 <span class="dropdown-text">OMOP CDM Presentation</span></a>
  </li>
        <li>
    <a class="dropdown-item" href="./dsomop.html"><i class="bi bi-database-fill" role="img">
</i>
 <span class="dropdown-text">dsOMOP Workshop</span></a>
  </li>
        <li>
    <a class="dropdown-item" href="./omop-exercises.html"><i class="bi bi-clipboard-check" role="img">
</i>
 <span class="dropdown-text">OMOP Exercises</span></a>
  </li>
        <li>
    <a class="dropdown-item" href="./gibleed.html"><i class="bi bi-droplet-half" role="img">
</i>
 <span class="dropdown-text">GiBleed Workshop</span></a>
  </li>
        <li>
    <a class="dropdown-item" href="./gibleed-exercises.html"><i class="bi bi-clipboard-check" role="img">
</i>
 <span class="dropdown-text">GiBleed Exercises</span></a>
  </li>
        <li>
    <a class="dropdown-item" href="./dsflower.html"><i class="bi bi-diagram-3-fill" role="img">
</i>
 <span class="dropdown-text">Federated ML (dsFlower)</span></a>
  </li>
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./schedule.html"> <i class="bi bi-calendar3" role="img">
</i>
<span class="menu-text">Schedule</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./resources.html"> <i class="bi bi-book-fill" role="img">
</i>
<span class="menu-text">Resources</span></a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./contact.html"> <i class="bi bi-envelope-fill" role="img">
</i>
<span class="menu-text">Contact</span></a>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/isglobal-brge"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i>
<span class="menu-text"></span></a>
  </li>
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/company/barcelona-institute-for-global-health-isglobal-"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i>
<span class="menu-text"></span></a>
  </li>
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.isglobal.org"> <i class="bi bi-globe" role="img" aria-label="ISGlobal Website">
</i>
<span class="menu-text"></span></a>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>

  <ul>
  <li><a href="#welcome" id="toc-welcome" class="nav-link active" data-scroll-target="#welcome">Welcome</a></li>
  <li><a href="#before-you-start-install-the-validated-dsomopclient" id="toc-before-you-start-install-the-validated-dsomopclient" class="nav-link" data-scroll-target="#before-you-start-install-the-validated-dsomopclient">Before you start: install the validated dsOMOPClient</a></li>
  <li><a href="#connecting-to-the-federation" id="toc-connecting-to-the-federation" class="nav-link" data-scroll-target="#connecting-to-the-federation">1. Connecting to the federation</a></li>
  <li><a href="#reading-the-map-tables-and-columns" id="toc-reading-the-map-tables-and-columns" class="nav-link" data-scroll-target="#reading-the-map-tables-and-columns">2. Reading the map: tables and columns</a></li>
  <li><a href="#who-are-these-patients" id="toc-who-are-these-patients" class="nav-link" data-scroll-target="#who-are-these-patients">3. Who are these patients?</a></li>
  <li><a href="#discovering-what-was-recorded" id="toc-discovering-what-was-recorded" class="nav-link" data-scroll-target="#discovering-what-was-recorded">4. Discovering what was recorded</a></li>
  <li><a href="#numeric-measurements-shape-matters" id="toc-numeric-measurements-shape-matters" class="nav-link" data-scroll-target="#numeric-measurements-shape-matters">5. Numeric measurements: shape matters</a></li>
  <li><a href="#a-categorical-measurement-heart-rhythm" id="toc-a-categorical-measurement-heart-rhythm" class="nav-link" data-scroll-target="#a-categorical-measurement-heart-rhythm">6. A categorical measurement: heart rhythm</a></li>
  <li><a href="#the-recipe-building-analysis-tables" id="toc-the-recipe-building-analysis-tables" class="nav-link" data-scroll-target="#the-recipe-building-analysis-tables">7. The recipe: building analysis tables</a>
  <ul class="collapse">
  <li><a href="#start-simple-sex-and-age" id="toc-start-simple-sex-and-age" class="nav-link" data-scroll-target="#start-simple-sex-and-age">7.1 Start simple — sex and age</a></li>
  <li><a href="#grow-it-numbers-flags-and-counts" id="toc-grow-it-numbers-flags-and-counts" class="nav-link" data-scroll-target="#grow-it-numbers-flags-and-counts">7.2 Grow it — numbers, flags and counts</a></li>
  <li><a href="#one-recipe-several-tables" id="toc-one-recipe-several-tables" class="nav-link" data-scroll-target="#one-recipe-several-tables">7.3 One recipe, several tables</a></li>
  </ul></li>
  <li><a href="#filtering-at-extraction" id="toc-filtering-at-extraction" class="nav-link" data-scroll-target="#filtering-at-extraction">8. Filtering at extraction</a>
  <ul class="collapse">
  <li><a href="#combine-criteria-and-or-and-nesting" id="toc-combine-criteria-and-or-and-nesting" class="nav-link" data-scroll-target="#combine-criteria-and-or-and-nesting">Combine criteria — AND, OR, and nesting</a></li>
  </ul></li>
  <li><a href="#a-real-model-what-predicts-a-diagnosis" id="toc-a-real-model-what-predicts-a-diagnosis" class="nav-link" data-scroll-target="#a-real-model-what-predicts-a-diagnosis">9. A real model: what predicts a diagnosis?</a></li>
  <li><a href="#where-to-go-next" id="toc-where-to-go-next" class="nav-link" data-scroll-target="#where-to-go-next">Where to go next</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Federated OMOP analysis with dsOMOP</h1>
<p class="subtitle lead">A hands-on tutorial — exploring real hospital data across three sites, without the data ever leaving them</p>
</div>



<div class="quarto-title-meta column-page-left">




  </div>



</header>


<p><a href="#" onclick="event.preventDefault(); fetch('https://raw.githubusercontent.com/isglobal-brge/workshop_DSWB/main/dsomop.R').then(response => response.blob()).then(blob => { const url = window.URL.createObjectURL(blob); const a = document.createElement('a'); a.style.display = 'none'; a.href = url; a.download = 'dsomop.R'; document.body.appendChild(a); a.click(); window.URL.revokeObjectURL(url); }); return false;" class="btn btn-primary btn-sm"> <i class="bi bi-download"></i> Download the R script (.R) </a> <a href="#" onclick="event.preventDefault(); fetch('https://raw.githubusercontent.com/isglobal-brge/workshop_DSWB/main/dsomop.Rmd').then(response => response.blob()).then(blob => { const url = window.URL.createObjectURL(blob); const a = document.createElement('a'); a.style.display = 'none'; a.href = url; a.download = 'dsomop.Rmd'; document.body.appendChild(a); a.click(); window.URL.revokeObjectURL(url); }); return false;" class="btn btn-outline-primary btn-sm"> <i class="bi bi-download"></i> Source (.Rmd) </a></p>
<section id="welcome" class="level1">
<h1>Welcome</h1>
<p>In this tutorial you will analyse <strong>real-world hospital data</strong> that lives in <strong>three different hospitals at once</strong> — and you will do it <strong>without ever seeing or downloading a single patient’s record</strong>.</p>
<ul>
<li><strong>OMOP CDM</strong> is a standard <em>shape</em> for health data: every hospital stores patients, diagnoses, drugs and labs in the same tables (<code>person</code>, <code>condition_occurrence</code>, <code>drug_exposure</code>, <code>measurement</code>, …).</li>
<li><strong>DataSHIELD</strong> is the safety layer: you send <em>commands</em>, each hospital runs them on its own data and returns <strong>only aggregated, non-disclosive results</strong>.</li>
<li><strong>dsOMOP</strong> is the bridge that lets DataSHIELD speak OMOP.</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>A small demo dataset — what to expect
</div>
</div>
<div class="callout-body-container callout-body">
<p>We work with a <strong>very small sample of OMOP CDM data</strong> (MIMIC, ~100 patients per site). Two consequences worth setting up front:</p>
<ul>
<li><strong>Privacy thresholds will bite often.</strong> Every result is checked by a disclosure filter on each server, and anything describing too few patients is withheld. On a tiny cohort these <strong>patient-count thresholds are reached easily</strong>, so some operations — narrow filters, rare concepts — may return nothing. On a large, real dataset this rarely happens; it is a property of the sample size, not a fault.</li>
<li><strong>Expect weak associations.</strong> With so few patients the analyses are underpowered, so effects are often small or non-significant. Again: a consequence of the demo’s size, not of the method.</li>
</ul>
</div>
</div>
<p>We work with <strong>MIMIC</strong> (an intensive-care database, ~100 patients here): connect → explore → learn the <strong>recipe</strong> for building analysis tables → filter → and finish with a real <strong>regression model</strong>.</p>
</section>
<section id="before-you-start-install-the-validated-dsomopclient" class="level1">
<h1>Before you start: install the validated dsOMOPClient</h1>
<p>These machines already have <strong><code>devtools</code></strong>. Install the client version used to validate this tutorial before anything else; pinning the tag keeps every participant on the same API:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>devtools<span class="sc">::</span><span class="fu">install_github</span>(</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"isglobal-brge/dsOMOPClient@2.7.1"</span>,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">force =</span> <span class="cn">TRUE</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">upgrade =</span> <span class="st">"never"</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>If R already had <code>dsOMOPClient</code> loaded, restart the session afterwards, then carry on.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Validated client/server pair
</div>
</div>
<div class="callout-body-container callout-body">
<p>This edition uses <strong>dsOMOPClient 2.7.1</strong> with <strong>dsOMOP 2.5.1</strong> on the servers (<code>davidsarrat/rock-dsomop-dswb-reproducibility:2.5.1</code>). The server profile is maintained centrally; workshop participants do not need server-administrator access.</p>
</div>
</div>
</section>
<section id="connecting-to-the-federation" class="level1">
<h1>1. Connecting to the federation</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DSI)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DSOpal)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dsBaseClient)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dsOMOPClient)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>builder <span class="ot">&lt;-</span> DSI<span class="sc">::</span><span class="fu">newDSLoginBuilder</span>()</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>builder<span class="sc">$</span><span class="fu">append</span>(<span class="at">server =</span> <span class="st">"nairobi"</span>, <span class="at">url =</span> <span class="st">"https://nairobi.datashield.live"</span>,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">user =</span> <span class="st">"ethiopia"</span>, <span class="at">password =</span> <span class="st">"P@ssw0rd"</span>, <span class="at">profile =</span> <span class="st">"omop"</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>builder<span class="sc">$</span><span class="fu">append</span>(<span class="at">server =</span> <span class="st">"douala"</span>,  <span class="at">url =</span> <span class="st">"https://douala.datashield.live"</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">user =</span> <span class="st">"ethiopia"</span>, <span class="at">password =</span> <span class="st">"P@ssw0rd"</span>, <span class="at">profile =</span> <span class="st">"omop"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>builder<span class="sc">$</span><span class="fu">append</span>(<span class="at">server =</span> <span class="st">"dakar"</span>,   <span class="at">url =</span> <span class="st">"https://dakar.datashield.live"</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">user =</span> <span class="st">"ethiopia"</span>, <span class="at">password =</span> <span class="st">"P@ssw0rd"</span>, <span class="at">profile =</span> <span class="st">"omop"</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>conns <span class="ot">&lt;-</span> DSI<span class="sc">::</span><span class="fu">datashield.login</span>(<span class="at">logins =</span> builder<span class="sc">$</span><span class="fu">build</span>())</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.omop.connect</span>(<span class="at">resource =</span> <span class="st">"omop_demo.mimic"</span>, <span class="at">symbol =</span> <span class="st">"omop"</span>, <span class="at">conns =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>If <code>ds.omop.connect()</code> reports unsafe <code>c</code>/<code>list</code> aggregate methods, the selected server profile is stale rather than your login being wrong. Ask the workshop maintainer to deploy the validated <code>dsOMOP 2.5.1</code> profile; do not weaken the client-side safety check.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Always select a profile
</div>
</div>
<div class="callout-body-container callout-body">
<p>The #1 beginner mistake is <strong>not selecting a profile</strong> at login. A DataSHIELD server can host several profiles (each a different set of installed packages), and the <strong>default</strong> profile here does <strong>not</strong> include dsOMOP. On these machines dsOMOP lives in the <strong><code>omop</code></strong> profile, so we pass <code>profile = "omop"</code> — without it, the <code>ds.omop.*</code> functions aren’t available.</p>
</div>
</div>
</section>
<section id="reading-the-map-tables-and-columns" class="level1">
<h1>2. Reading the map: tables and columns</h1>
<p>The clinical (<code>CDM</code>) tables (consistent across the three sites, so one view represents the federation):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>tabs <span class="ot">&lt;-</span> <span class="fu">ds.omop.tables</span>(<span class="at">symbol =</span> <span class="st">"omop"</span>, <span class="at">conns =</span> conns)[[<span class="dv">1</span>]]</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>tabs[tabs<span class="sc">$</span>schema_category <span class="sc">==</span> <span class="st">"CDM"</span>, <span class="fu">c</span>(<span class="st">"table_name"</span>, <span class="st">"has_person_id"</span>)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;              table_name has_person_id
#&gt; 1                person          TRUE
#&gt; 2    observation_period          TRUE
#&gt; 3      visit_occurrence          TRUE
#&gt; 4          visit_detail          TRUE
#&gt; 5  condition_occurrence          TRUE
#&gt; 6         drug_exposure          TRUE
#&gt; 7  procedure_occurrence          TRUE
#&gt; 8       device_exposure          TRUE
#&gt; 9           measurement          TRUE
#&gt; 10          observation          TRUE
#&gt; 11                death          TRUE
#&gt; 12                 note          TRUE
#&gt; 13             note_nlp         FALSE
#&gt; 14             specimen          TRUE
#&gt; 15    fact_relationship         FALSE
#&gt; 16             location         FALSE
#&gt; 17            care_site         FALSE
#&gt; 18             provider         FALSE
#&gt; 19    payer_plan_period          TRUE
#&gt; 20                 cost         FALSE
#&gt; 21             drug_era          TRUE
#&gt; 22             dose_era          TRUE
#&gt; 23        condition_era          TRUE
#&gt; 24             metadata         FALSE
#&gt; 25           cdm_source         FALSE</code></pre>
</div>
</div>
<p>The columns of the <code>measurement</code> table (where labs and vital signs live):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.omop.columns</span>(<span class="st">"measurement"</span>, <span class="at">symbol =</span> <span class="st">"omop"</span>, <span class="at">conns =</span> conns)[[<span class="dv">1</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;                      column_name cdm_datatype                 db_datatype      concept_role    fk_domain is_date is_extension is_untyped_identifier is_sensitive is_blocked
#&gt; 1                 measurement_id      integer                      bigint       non_concept                FALSE        FALSE                 FALSE        FALSE      FALSE
#&gt; 2                      person_id      integer                      bigint       non_concept                FALSE        FALSE                 FALSE        FALSE      FALSE
#&gt; 3         measurement_concept_id      integer                      bigint    domain_concept  Measurement   FALSE        FALSE                 FALSE        FALSE      FALSE
#&gt; 4               measurement_date         date                        date       non_concept                 TRUE        FALSE                 FALSE        FALSE      FALSE
#&gt; 5           measurement_datetime     datetime timestamp without time zone       non_concept                 TRUE        FALSE                 FALSE        FALSE      FALSE
#&gt; 6               measurement_time  varchar(10)                        text       non_concept                FALSE        FALSE                 FALSE        FALSE      FALSE
#&gt; 7    measurement_type_concept_id      integer                      bigint      type_concept Type Concept   FALSE        FALSE                 FALSE        FALSE      FALSE
#&gt; 8            operator_concept_id      integer                      bigint attribute_concept                FALSE        FALSE                 FALSE        FALSE      FALSE
#&gt; 9                value_as_number        float                     numeric       non_concept                FALSE        FALSE                 FALSE        FALSE      FALSE
#&gt; 10           value_as_concept_id      integer                      bigint attribute_concept                FALSE        FALSE                 FALSE        FALSE      FALSE
#&gt; 11               unit_concept_id      integer                      bigint attribute_concept         Unit   FALSE        FALSE                 FALSE        FALSE      FALSE
#&gt; 12                     range_low        float                     numeric       non_concept                FALSE        FALSE                 FALSE        FALSE      FALSE
#&gt; 13                    range_high        float                     numeric       non_concept                FALSE        FALSE                 FALSE        FALSE      FALSE
#&gt; 14                   provider_id      integer                      bigint       non_concept                FALSE        FALSE                 FALSE        FALSE      FALSE
#&gt; 15           visit_occurrence_id      integer                      bigint       non_concept                FALSE        FALSE                 FALSE        FALSE      FALSE
#&gt; 16               visit_detail_id      integer                      bigint       non_concept                FALSE        FALSE                 FALSE        FALSE      FALSE
#&gt; 17      measurement_source_value  varchar(50)                        text       non_concept                FALSE        FALSE                 FALSE         TRUE       TRUE
#&gt; 18 measurement_source_concept_id      integer                      bigint    source_concept                FALSE        FALSE                 FALSE         TRUE       TRUE
#&gt; 19             unit_source_value  varchar(50)                        text       non_concept                FALSE        FALSE                 FALSE         TRUE       TRUE
#&gt; 20            value_source_value  varchar(50)                        text       non_concept                FALSE        FALSE                 FALSE         TRUE       TRUE</code></pre>
</div>
</div>
</section>
<section id="who-are-these-patients" class="level1">
<h1>3. Who are these patients?</h1>
<p>Gender, <strong>pooled</strong> across the three sites:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.omop.concept.prevalence</span>(<span class="st">"person"</span>, <span class="at">concept_col =</span> <span class="st">"gender_concept_id"</span>,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">scope =</span> <span class="st">"pooled"</span>, <span class="at">symbol =</span> <span class="st">"omop"</span>, <span class="at">conns =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; &lt;dsomop_result&gt;
#&gt; Servers: nairobi, douala, dakar
#&gt; Scope: pooled
#&gt;
#&gt; $nairobi
#&gt;   concept_id concept_name n_persons n_records
#&gt; 1       8507         MALE        15        15
#&gt; 2       8532       FEMALE        15        15
#&gt;
#&gt; $douala
#&gt;   concept_id concept_name n_persons n_records
#&gt; 1       8507         MALE        15        15
#&gt; 2       8532       FEMALE         5         5
#&gt;
#&gt; $dakar
#&gt;   concept_id concept_name n_persons n_records
#&gt; 1       8507         MALE        25        25
#&gt; 2       8532       FEMALE        15        15
#&gt;
#&gt; $pooled
#&gt;   concept_id n_persons concept_name
#&gt; 1       8507        55         MALE
#&gt; 2       8532        35       FEMALE
#&gt;
#&gt; Warnings:
#&gt;   - Federated counts are sums of per-site banded lower bounds (width 5); count-weighted means and variances are therefore approximate, not reconstructed exact pooled statistics.</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Concepts translate themselves
</div>
</div>
<div class="callout-body-container callout-body">
<p>You got <code>MALE</code> / <code>FEMALE</code>, not codes like <code>8507</code> / <code>8532</code> — any <code>*_concept_id</code> column is automatically translated. <strong>Concept translation is on by default.</strong></p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Raw birth dates and birth years remain protected. In Section 7 the recipe asks dsOMOP to derive age inside each server, so the source values never leave the DataSHIELD session.</p>
</div>
</div>
</section>
<section id="discovering-what-was-recorded" class="level1">
<h1>4. Discovering what was recorded</h1>
<p>The most common diagnoses, <strong>pooled</strong> and ranked by distinct patients:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.omop.concept.prevalence</span>(<span class="st">"condition_occurrence"</span>, <span class="at">metric =</span> <span class="st">"persons"</span>,</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                           <span class="at">top_n =</span> <span class="dv">10</span>, <span class="at">scope =</span> <span class="st">"pooled"</span>, <span class="at">symbol =</span> <span class="st">"omop"</span>, <span class="at">conns =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; &lt;dsomop_result&gt;
#&gt; Servers: nairobi, douala, dakar
#&gt; Scope: pooled
#&gt;
#&gt; $nairobi
#&gt;    concept_id                     concept_name n_persons n_records
#&gt; 1     4145513                ECG: sinus rhythm        30      2405
#&gt; 2     4140598           ECG: sinus tachycardia        20       625
#&gt; 3      320128           Essential hypertension        15        35
#&gt; 4      432867                   Hyperlipidemia        15        40
#&gt; 5      433753                    Alcohol abuse        15        55
#&gt; 6       81902 Urinary tract infectious disease        10        20
#&gt; 7      197320              Acute kidney injury        10        25
#&gt; 8      313217              Atrial fibrillation        10        20
#&gt; 9      439777                           Anemia        10        15
#&gt; 10     440383              Depressive disorder        10        20
#&gt;
#&gt; $douala
#&gt;    concept_id                          concept_name n_persons n_records
#&gt; 1     4145513                     ECG: sinus rhythm        20      1750
#&gt; 2      433753                         Alcohol abuse        15        60
#&gt; 3     4140598                ECG: sinus tachycardia        15      1100
#&gt; 4      197320                   Acute kidney injury        10        25
#&gt; 5      320128                Essential hypertension        10        30
#&gt; 6      432867                        Hyperlipidemia        10        40
#&gt; 7     4138456                ECG: sinus bradycardia        10        65
#&gt; 8      140673                        Hypothyroidism         5        35
#&gt; 9      254061                      Pleural effusion         5         5
#&gt; 10     255573 Chronic obstructive pulmonary disease         5         5
#&gt;
#&gt; $dakar
#&gt;    concept_id                     concept_name n_persons n_records
#&gt; 1     4145513                ECG: sinus rhythm        35      2375
#&gt; 2      433753                    Alcohol abuse        25        60
#&gt; 3     4140598           ECG: sinus tachycardia        25       575
#&gt; 4      320128           Essential hypertension        20        30
#&gt; 5      432867                   Hyperlipidemia        20        30
#&gt; 6      197320              Acute kidney injury        10        10
#&gt; 7      442019        Complication of procedure        10        10
#&gt; 8       81902 Urinary tract infectious disease         5         5
#&gt; 9      313217              Atrial fibrillation         5        10
#&gt; 10     317002               Low blood pressure         5         5
#&gt;
#&gt; $pooled
#&gt;   concept_id n_persons           concept_name
#&gt; 1    4145513        85      ECG: sinus rhythm
#&gt; 2    4140598        60 ECG: sinus tachycardia
#&gt; 3     433753        55          Alcohol abuse
#&gt; 4     320128        45 Essential hypertension
#&gt; 5     432867        45         Hyperlipidemia
#&gt; 6     197320        30    Acute kidney injury
#&gt;
#&gt; Warnings:
#&gt;   - Federated counts are sums of per-site banded lower bounds (width 5); count-weighted means and variances are therefore approximate, not reconstructed exact pooled statistics.</code></pre>
</div>
</div>
<p>Don’t know a concept’s code? <strong>Search</strong> for it. The search accepts normal words: spaces and punctuation do not have to match the vocabulary spelling.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.omop.concept.search</span>(<span class="st">"infarction / myocardial-acute"</span>, <span class="at">domain =</span> <span class="st">"Condition"</span>,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">limit =</span> <span class="dv">5</span>, <span class="at">symbol =</span> <span class="st">"omop"</span>, <span class="at">conns =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; &lt;dsomop_result&gt;
#&gt; Servers: nairobi, douala, dakar
#&gt; Scope: pooled
#&gt;
#&gt; $nairobi
#&gt;   concept_id                                         concept_name domain_id vocabulary_id standard_concept concept_class_id concept_code valid_start_date valid_end_date invalid_reason
#&gt; 1     312327                          Acute myocardial infarction Condition        SNOMED                S         Disorder     57054005       1970-01-01     2099-12-31           &lt;NA&gt;
#&gt; 2    4270024 Acute non-ST segment elevation myocardial infarction Condition        SNOMED                S         Disorder    401314000       1970-01-01     2099-12-31           &lt;NA&gt;
#&gt;
#&gt; $douala
#&gt;   concept_id                                         concept_name domain_id vocabulary_id standard_concept concept_class_id concept_code valid_start_date valid_end_date invalid_reason
#&gt; 1     312327                          Acute myocardial infarction Condition        SNOMED                S         Disorder     57054005       1970-01-01     2099-12-31           &lt;NA&gt;
#&gt; 2    4270024 Acute non-ST segment elevation myocardial infarction Condition        SNOMED                S         Disorder    401314000       1970-01-01     2099-12-31           &lt;NA&gt;
#&gt;
#&gt; $dakar
#&gt;   concept_id                                         concept_name domain_id vocabulary_id standard_concept concept_class_id concept_code valid_start_date valid_end_date invalid_reason
#&gt; 1     312327                          Acute myocardial infarction Condition        SNOMED                S         Disorder     57054005       1970-01-01     2099-12-31           &lt;NA&gt;
#&gt; 2    4270024 Acute non-ST segment elevation myocardial infarction Condition        SNOMED                S         Disorder    401314000       1970-01-01     2099-12-31           &lt;NA&gt;
#&gt;
#&gt; $pooled
#&gt;   concept_id                                         concept_name domain_id vocabulary_id standard_concept concept_class_id concept_code valid_start_date valid_end_date invalid_reason
#&gt; 1     312327                          Acute myocardial infarction Condition        SNOMED                S         Disorder     57054005       1970-01-01     2099-12-31           &lt;NA&gt;
#&gt; 2    4270024 Acute non-ST segment elevation myocardial infarction Condition        SNOMED                S         Disorder    401314000       1970-01-01     2099-12-31           &lt;NA&gt;</code></pre>
</div>
</div>
<p>And <strong>look up</strong> codes you already have:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.omop.concept.lookup</span>(<span class="fu">c</span>(<span class="dv">320128</span>, <span class="dv">432867</span>, <span class="dv">3027018</span>), <span class="at">symbol =</span> <span class="st">"omop"</span>, <span class="at">conns =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; &lt;dsomop_result&gt;
#&gt; Servers: nairobi, douala, dakar
#&gt; Scope: pooled
#&gt;
#&gt; $nairobi
#&gt;   concept_id           concept_name   domain_id vocabulary_id standard_concept
#&gt; 1     320128 Essential hypertension   Condition        SNOMED                S
#&gt; 2     432867         Hyperlipidemia   Condition        SNOMED                S
#&gt; 3    3027018             Heart rate Measurement         LOINC                S
#&gt;
#&gt; $douala
#&gt;   concept_id           concept_name   domain_id vocabulary_id standard_concept
#&gt; 1     320128 Essential hypertension   Condition        SNOMED                S
#&gt; 2     432867         Hyperlipidemia   Condition        SNOMED                S
#&gt; 3    3027018             Heart rate Measurement         LOINC                S
#&gt;
#&gt; $dakar
#&gt;   concept_id           concept_name   domain_id vocabulary_id standard_concept
#&gt; 1     320128 Essential hypertension   Condition        SNOMED                S
#&gt; 2     432867         Hyperlipidemia   Condition        SNOMED                S
#&gt; 3    3027018             Heart rate Measurement         LOINC                S
#&gt;
#&gt; $pooled
#&gt;   concept_id           concept_name   domain_id vocabulary_id standard_concept
#&gt; 1     320128 Essential hypertension   Condition        SNOMED                S
#&gt; 2     432867         Hyperlipidemia   Condition        SNOMED                S
#&gt; 3    3027018             Heart rate Measurement         LOINC                S</code></pre>
</div>
</div>
</section>
<section id="numeric-measurements-shape-matters" class="level1">
<h1>5. Numeric measurements: shape matters</h1>
<p><code>ds.omop.column.stats()</code> returns a disclosure-safe summary (counts, mean, sd, a 5th–95th-percentile band — never the true min/max). Heart rate (<code>3027018</code>):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.omop.column.stats</span>(<span class="st">"measurement"</span>, <span class="st">"value_as_number"</span>, <span class="at">concept_id =</span> <span class="dv">3027018</span>,</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">scope =</span> <span class="st">"pooled"</span>, <span class="at">symbol =</span> <span class="st">"omop"</span>, <span class="at">conns =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; &lt;dsomop_result&gt;
#&gt; Servers: nairobi, douala, dakar
#&gt; Scope: pooled
#&gt;
#&gt; $nairobi
#&gt; $n_total
#&gt; [1] 9700
#&gt;
#&gt; $n_missing
#&gt; [1] 0
#&gt;
#&gt; $n_distinct
#&gt; [1] NA
#&gt;
#&gt; $n_persons
#&gt; [1] 35
#&gt;
#&gt; $mean
#&gt; [1] 88.6399
#&gt;
#&gt; $sd
#&gt; [1] 12.9859
#&gt;
#&gt;
#&gt; $douala
#&gt; $n_total
#&gt; [1] 5155
#&gt;
#&gt; $n_missing
#&gt; [1] 0
#&gt;
#&gt; $n_distinct
#&gt; [1] NA
#&gt;
#&gt; $n_persons
#&gt; [1] 25
#&gt;
#&gt; $mean
#&gt; [1] 89.6812
#&gt;
#&gt; $sd
#&gt; [1] 13.2828
#&gt;
#&gt;
#&gt; $dakar
#&gt; $n_total
#&gt; [1] 4460
#&gt;
#&gt; $n_missing
#&gt; [1] 0
#&gt;
#&gt; $n_distinct
#&gt; [1] NA
#&gt;
#&gt; $n_persons
#&gt; [1] 40
#&gt;
#&gt; $mean
#&gt; [1] 87.1013
#&gt;
#&gt; $sd
#&gt; [1] 13.1074
#&gt;
#&gt;
#&gt; $pooled
#&gt; $n_total
#&gt; [1] 19315
#&gt;
#&gt; $mean
#&gt; [1] 88.28478
#&gt;
#&gt; $n_persons
#&gt; [1] 100
#&gt;
#&gt; $n_missing
#&gt; [1] 0
#&gt;
#&gt; $sd
#&gt; [1] 13.01804
#&gt;
#&gt;
#&gt; Warnings:
#&gt;   - Federated counts are sums of per-site banded lower bounds (width 5); count-weighted means and variances are therefore approximate, not reconstructed exact pooled statistics.</code></pre>
</div>
</div>
<p>Its distribution — again with <code>plot = TRUE</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.omop.value.histogram</span>(<span class="st">"measurement"</span>, <span class="at">value_col =</span> <span class="st">"value_as_number"</span>, <span class="at">concept_id =</span> <span class="dv">3027018</span>,</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>                        <span class="at">bins =</span> <span class="dv">3</span>, <span class="at">nbins =</span> <span class="dv">3</span>, <span class="at">plot =</span> <span class="cn">TRUE</span>, <span class="at">xlab =</span> <span class="st">"Heart rate (bpm)"</span>,</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">main =</span> <span class="st">"Heart rate (pooled across sites)"</span>,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">symbol =</span> <span class="st">"omop"</span>, <span class="at">conns =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="dsomop_files/figure-html/hr-hist-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Shared bins
</div>
</div>
<div class="callout-body-container callout-body">
<p>Federated histograms use the same bin edges at every site and combine only disclosure-safe bin counts. With this small teaching dataset, three broad bins keep every site represented in the pooled plot.</p>
</div>
</div>
</section>
<section id="a-categorical-measurement-heart-rhythm" class="level1">
<h1>6. A categorical measurement: heart rhythm</h1>
<p>Some measurements store a <em>category</em> in <code>value_as_concept_id</code> instead of a number. Heart <strong>rhythm</strong> is the measurement concept <code>3022318</code>; its recorded answers live in <code>value_as_concept_id</code>. Count them, pooled:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.omop.value.counts</span>(<span class="st">"measurement"</span>, <span class="st">"value_as_concept_id"</span>, <span class="at">concept_id =</span> <span class="dv">3022318</span>,</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">scope =</span> <span class="st">"pooled"</span>, <span class="at">symbol =</span> <span class="st">"omop"</span>, <span class="at">conns =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; &lt;dsomop_result&gt;
#&gt; Servers: nairobi, douala, dakar
#&gt; Scope: pooled
#&gt;
#&gt; $nairobi
#&gt;      value    n n_persons        concept_name
#&gt; 1 45877096 2405        30        Sinus rhythm
#&gt; 2 45883018 1280        10 Atrial fibrillation
#&gt; 3 45879290  625        20   Sinus tachycardia
#&gt; 4 21499419  245         5   Sinus bradycardia
#&gt; 5        0   30         5 No matching concept
#&gt;
#&gt; $douala
#&gt;      value    n n_persons        concept_name
#&gt; 1 45877096 1750        20        Sinus rhythm
#&gt; 2 45879290 1100        15   Sinus tachycardia
#&gt; 3        0  585         0 No matching concept
#&gt; 4 45883018  405         5 Atrial fibrillation
#&gt; 5 21499419   65        10   Sinus bradycardia
#&gt;
#&gt; $dakar
#&gt;      value    n n_persons        concept_name
#&gt; 1 45877096 2375        35        Sinus rhythm
#&gt; 2 45883018  715         5 Atrial fibrillation
#&gt; 3 45879290  575        25   Sinus tachycardia
#&gt; 4 21499419   75         5   Sinus bradycardia
#&gt; 5 45884784   55         0 AV block-1st degree
#&gt; 6        0   50         5 No matching concept
#&gt;
#&gt; $pooled
#&gt;      n        concept_name    value
#&gt; 1 6530        Sinus rhythm 45877096
#&gt; 2 2400 Atrial fibrillation 45883018
#&gt; 3 2300   Sinus tachycardia 45879290
#&gt; 4  665 No matching concept        0
#&gt; 5  385   Sinus bradycardia 21499419
#&gt;
#&gt; Warnings:
#&gt;   - Federated counts are sums of per-site banded lower bounds (width 5); count-weighted means and variances are therefore approximate, not reconstructed exact pooled statistics.</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>How to read this
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>The first argument (<code>"measurement"</code>) is the <strong>table</strong> we look in; <code>concept_id = 3022318</code> is the measurement; <code>value_as_concept_id</code> is the column we count. (For a social fact you’d look in <code>"observation"</code> instead.)</li>
<li><strong><code>concept_name</code></strong> is each answer’s translated label; <strong><code>value</code></strong> is its raw concept code (e.g.&nbsp;<code>45877096</code> = “Sinus rhythm”).</li>
<li><strong>“No matching concept”</strong> (value <code>0</code>) is OMOP’s reserved label for records whose value didn’t map to a standard concept — <em>not</em> suppression and not a bug.</li>
</ul>
</div>
</div>
</section>
<section id="the-recipe-building-analysis-tables" class="level1">
<h1>7. The recipe: building analysis tables</h1>
<p>To <strong>model</strong> anything we need one row per patient and one column per variable. You describe that table with a <strong>recipe</strong>; the servers build it for you. Every recipe has the same shape — here is the skeleton (don’t run this; it’s a template):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">omop_recipe</span>(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="fu">list</span>(    <span class="co"># WHAT columns you want</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">omop_variable</span>(),       <span class="co"># a person column, or something built from a concept_id</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">omop_variable_age</span>(),   <span class="co"># the patient's age</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">omop_variable</span>()        <span class="co"># ...add as many as you need</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">filters =</span> <span class="fu">list</span>(),    <span class="co"># OPTIONAL: restrict the population (Section 8)</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">output  =</span> <span class="fu">omop_output</span>()  <span class="co"># the table SHAPE you want (usually wide = one row/patient)</span></span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a><span class="fu">recipe_execute</span>()       <span class="co"># build it on each server into a named symbol</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="start-simple-sex-and-age" class="level2">
<h2 data-anchor-id="start-simple-sex-and-age">7.1 Start simple — sex and age</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>rec0 <span class="ot">&lt;-</span> <span class="fu">omop_recipe</span>(</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="fu">list</span>(</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">omop_variable</span>(<span class="at">table =</span> <span class="st">"person"</span>, <span class="at">column =</span> <span class="st">"gender_concept_id"</span>, <span class="at">format =</span> <span class="st">"sex_mf"</span>, <span class="at">name =</span> <span class="st">"sex"</span>),</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">omop_variable_age</span>(<span class="at">name =</span> <span class="st">"age"</span>, <span class="at">year =</span> <span class="dv">2024</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">output =</span> <span class="fu">omop_output</span>(<span class="at">name =</span> <span class="st">"study"</span>, <span class="at">type =</span> <span class="st">"wide"</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a><span class="fu">recipe_execute</span>(rec0, <span class="at">out =</span> <span class="fu">c</span>(<span class="at">study =</span> <span class="st">"M0"</span>), <span class="at">symbol =</span> <span class="st">"omop"</span>, <span class="at">conns =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Always inspect what the server built</strong>, then look at each variable:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.colnames</span>(<span class="st">"M0"</span>, <span class="at">datasources =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; $nairobi
#&gt; [1] "person_id" "sex"       "age"
#&gt;
#&gt; $douala
#&gt; [1] "person_id" "sex"       "age"
#&gt;
#&gt; $dakar
#&gt; [1] "person_id" "sex"       "age"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.dim</span>(<span class="st">"M0"</span>, <span class="at">datasources =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; $`dimensions of M0 in nairobi`
#&gt; [1] 35  3
#&gt;
#&gt; $`dimensions of M0 in douala`
#&gt; [1] 25  3
#&gt;
#&gt; $`dimensions of M0 in dakar`
#&gt; [1] 40  3
#&gt;
#&gt; $`dimensions of M0 in combined studies`
#&gt; [1] 100   3</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.table</span>(<span class="st">"M0$sex"</span>, <span class="at">datasources =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; $output.list
#&gt; $output.list$TABLE_rvar.by.study_row.props
#&gt;       study
#&gt; M0$sex   nairobi    douala     dakar
#&gt;     F  0.4418605 0.2093023 0.3488372
#&gt;     M  0.2807018 0.2807018 0.4385965
#&gt;     NA       NaN       NaN       NaN
#&gt;
#&gt; $output.list$TABLE_rvar.by.study_col.props
#&gt;       study
#&gt; M0$sex   nairobi douala dakar
#&gt;     F  0.5428571   0.36 0.375
#&gt;     M  0.4571429   0.64 0.625
#&gt;     NA 0.0000000   0.00 0.000
#&gt;
#&gt; $output.list$TABLE_rvar.by.study_counts
#&gt;       study
#&gt; M0$sex nairobi douala dakar
#&gt;     F       19      9    15
#&gt;     M       16     16    25
#&gt;     NA       0      0     0
#&gt;
#&gt; $output.list$TABLES.COMBINED_all.sources_proportions
#&gt; M0$sex
#&gt;    F    M   NA
#&gt; 0.43 0.57 0.00
#&gt;
#&gt; $output.list$TABLES.COMBINED_all.sources_counts
#&gt; M0$sex
#&gt;  F  M NA
#&gt; 43 57  0
#&gt;
#&gt;
#&gt; $validity.message
#&gt; [1] "Data in all studies were valid"</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.summary</span>(<span class="st">"M0$age"</span>, <span class="at">datasources =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; $nairobi
#&gt; $nairobi$class
#&gt; [1] "integer"
#&gt;
#&gt; $nairobi$length
#&gt; [1] 35
#&gt;
#&gt; $nairobi$`quantiles &amp; mean`
#&gt;       5%      10%      25%      50%      75%      90%      95%     Mean
#&gt; 38.90000 46.40000 52.00000 63.00000 76.50000 86.00000 88.90000 63.88571
#&gt;
#&gt;
#&gt; $douala
#&gt; $douala$class
#&gt; [1] "integer"
#&gt;
#&gt; $douala$length
#&gt; [1] 25
#&gt;
#&gt; $douala$`quantiles &amp; mean`
#&gt;   5%  10%  25%  50%  75%  90%  95% Mean
#&gt; 34.8 39.6 46.0 58.0 69.0 84.2 85.8 59.0
#&gt;
#&gt;
#&gt; $dakar
#&gt; $dakar$class
#&gt; [1] "integer"
#&gt;
#&gt; $dakar$length
#&gt; [1] 40
#&gt;
#&gt; $dakar$`quantiles &amp; mean`
#&gt;     5%    10%    25%    50%    75%    90%    95%   Mean
#&gt; 32.750 47.600 59.000 65.500 74.250 83.100 88.050 64.975</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why <code>year = 2024</code>?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Age needs a reference year. This extract runs through 2024, so we anchor age there rather than to “today” (which would drift on every rebuild). The age <strong>filter</strong> in Section 8 takes the same <code>year =</code>.</p>
</div>
</div>
</section>
<section id="grow-it-numbers-flags-and-counts" class="level2">
<h2 data-anchor-id="grow-it-numbers-flags-and-counts">7.2 Grow it — numbers, flags and counts</h2>
<p>Mix the variable types we met: a categorical (<code>sex</code>), a numeric mean (<code>heart_rate</code>), two <strong>binary</strong> condition flags, and a <strong>count</strong> (<code>n_visits</code>):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>rec <span class="ot">&lt;-</span> <span class="fu">omop_recipe</span>(</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="fu">list</span>(</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">omop_variable</span>(<span class="at">table =</span> <span class="st">"person"</span>, <span class="at">column =</span> <span class="st">"gender_concept_id"</span>, <span class="at">format =</span> <span class="st">"sex_mf"</span>, <span class="at">name =</span> <span class="st">"sex"</span>),</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">omop_variable_age</span>(<span class="at">name =</span> <span class="st">"age"</span>, <span class="at">year =</span> <span class="dv">2024</span>),</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">omop_variable</span>(<span class="at">table =</span> <span class="st">"measurement"</span>, <span class="at">concept_id =</span> <span class="dv">3027018</span>, <span class="at">format =</span> <span class="st">"mean"</span>, <span class="at">name =</span> <span class="st">"heart_rate"</span>),</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">omop_variable</span>(<span class="at">table =</span> <span class="st">"condition_occurrence"</span>, <span class="at">concept_id =</span> <span class="dv">320128</span>, <span class="at">format =</span> <span class="st">"binary"</span>, <span class="at">name =</span> <span class="st">"hypertension"</span>),</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">omop_variable</span>(<span class="at">table =</span> <span class="st">"condition_occurrence"</span>, <span class="at">concept_id =</span> <span class="dv">432867</span>, <span class="at">format =</span> <span class="st">"binary"</span>, <span class="at">name =</span> <span class="st">"hyperlipidemia"</span>),</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">omop_variable</span>(<span class="at">table =</span> <span class="st">"visit_occurrence"</span>, <span class="at">format =</span> <span class="st">"count"</span>, <span class="at">name =</span> <span class="st">"n_visits"</span>)</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">output =</span> <span class="fu">omop_output</span>(<span class="at">name =</span> <span class="st">"study"</span>, <span class="at">type =</span> <span class="st">"wide"</span>)</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a><span class="fu">recipe_execute</span>(rec, <span class="at">out =</span> <span class="fu">c</span>(<span class="at">study =</span> <span class="st">"M"</span>), <span class="at">symbol =</span> <span class="st">"omop"</span>, <span class="at">conns =</span> conns)</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.colnames</span>(<span class="st">"M"</span>, <span class="at">datasources =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; $nairobi
#&gt; [1] "person_id"      "heart_rate"     "hypertension"   "hyperlipidemia" "n_visits"       "sex"            "age"
#&gt;
#&gt; $douala
#&gt; [1] "person_id"      "heart_rate"     "hypertension"   "hyperlipidemia" "n_visits"       "sex"            "age"
#&gt;
#&gt; $dakar
#&gt; [1] "person_id"      "heart_rate"     "hypertension"   "hyperlipidemia" "n_visits"       "sex"            "age"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.dim</span>(<span class="st">"M"</span>, <span class="at">datasources =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; $`dimensions of M in nairobi`
#&gt; [1] 35  7
#&gt;
#&gt; $`dimensions of M in douala`
#&gt; [1] 25  7
#&gt;
#&gt; $`dimensions of M in dakar`
#&gt; [1] 40  7
#&gt;
#&gt; $`dimensions of M in combined studies`
#&gt; [1] 100   7</code></pre>
</div>
</div>
<p><strong>Look at every variable in its natural way.</strong> Numeric columns → a quantile summary:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.summary</span>(<span class="st">"M$age"</span>,        <span class="at">datasources =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; $nairobi
#&gt; $nairobi$class
#&gt; [1] "integer"
#&gt;
#&gt; $nairobi$length
#&gt; [1] 35
#&gt;
#&gt; $nairobi$`quantiles &amp; mean`
#&gt;       5%      10%      25%      50%      75%      90%      95%     Mean
#&gt; 38.90000 46.40000 52.00000 63.00000 76.50000 86.00000 88.90000 63.88571
#&gt;
#&gt;
#&gt; $douala
#&gt; $douala$class
#&gt; [1] "integer"
#&gt;
#&gt; $douala$length
#&gt; [1] 25
#&gt;
#&gt; $douala$`quantiles &amp; mean`
#&gt;   5%  10%  25%  50%  75%  90%  95% Mean
#&gt; 34.8 39.6 46.0 58.0 69.0 84.2 85.8 59.0
#&gt;
#&gt;
#&gt; $dakar
#&gt; $dakar$class
#&gt; [1] "integer"
#&gt;
#&gt; $dakar$length
#&gt; [1] 40
#&gt;
#&gt; $dakar$`quantiles &amp; mean`
#&gt;     5%    10%    25%    50%    75%    90%    95%   Mean
#&gt; 32.750 47.600 59.000 65.500 74.250 83.100 88.050 64.975</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.summary</span>(<span class="st">"M$heart_rate"</span>, <span class="at">datasources =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; $nairobi
#&gt; $nairobi$class
#&gt; [1] "numeric"
#&gt;
#&gt; $nairobi$length
#&gt; [1] 35
#&gt;
#&gt; $nairobi$`quantiles &amp; mean`
#&gt;        5%       10%       25%       50%       75%       90%       95%      Mean
#&gt;  68.85334  70.28388  78.92535  88.44355  98.68583 104.52308 107.79092  88.63992
#&gt;
#&gt;
#&gt; $douala
#&gt; $douala$class
#&gt; [1] "numeric"
#&gt;
#&gt; $douala$length
#&gt; [1] 25
#&gt;
#&gt; $douala$`quantiles &amp; mean`
#&gt;        5%       10%       25%       50%       75%       90%       95%      Mean
#&gt;  73.13263  77.11273  79.79085  86.91329  96.96841 108.92189 110.63490  89.68117
#&gt;
#&gt;
#&gt; $dakar
#&gt; $dakar$class
#&gt; [1] "numeric"
#&gt;
#&gt; $dakar$length
#&gt; [1] 40
#&gt;
#&gt; $dakar$`quantiles &amp; mean`
#&gt;        5%       10%       25%       50%       75%       90%       95%      Mean
#&gt;  66.18848  68.79545  76.51913  86.10011  96.25817 106.42000 107.06135  87.10134</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.summary</span>(<span class="st">"M$n_visits"</span>,   <span class="at">datasources =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; $nairobi
#&gt; $nairobi$class
#&gt; [1] "integer"
#&gt;
#&gt; $nairobi$length
#&gt; [1] 35
#&gt;
#&gt; $nairobi$`quantiles &amp; mean`
#&gt;       5%      10%      25%      50%      75%      90%      95%     Mean
#&gt;  1.00000  1.00000  1.50000  3.00000  8.50000 29.80000 39.20000 10.54286
#&gt;
#&gt;
#&gt; $douala
#&gt; $douala$class
#&gt; [1] "integer"
#&gt;
#&gt; $douala$length
#&gt; [1] 25
#&gt;
#&gt; $douala$`quantiles &amp; mean`
#&gt;    5%   10%   25%   50%   75%   90%   95%  Mean
#&gt;  1.00  1.00  2.00  3.00 14.00 26.00 62.00 12.92
#&gt;
#&gt;
#&gt; $dakar
#&gt; $dakar$class
#&gt; [1] "integer"
#&gt;
#&gt; $dakar$length
#&gt; [1] 40
#&gt;
#&gt; $dakar$`quantiles &amp; mean`
#&gt;   5%  10%  25%  50%  75%  90%  95% Mean
#&gt;  1.0  1.0  1.0  2.0  4.0  8.3 13.1  4.0</code></pre>
</div>
</div>
<p>Categorical / binary columns → a frequency table:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.table</span>(<span class="st">"M$sex"</span>,            <span class="at">datasources =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; $output.list
#&gt; $output.list$TABLE_rvar.by.study_row.props
#&gt;      study
#&gt; M$sex   nairobi    douala     dakar
#&gt;    F  0.4418605 0.2093023 0.3488372
#&gt;    M  0.2807018 0.2807018 0.4385965
#&gt;    NA       NaN       NaN       NaN
#&gt;
#&gt; $output.list$TABLE_rvar.by.study_col.props
#&gt;      study
#&gt; M$sex   nairobi douala dakar
#&gt;    F  0.5428571   0.36 0.375
#&gt;    M  0.4571429   0.64 0.625
#&gt;    NA 0.0000000   0.00 0.000
#&gt;
#&gt; $output.list$TABLE_rvar.by.study_counts
#&gt;      study
#&gt; M$sex nairobi douala dakar
#&gt;    F       19      9    15
#&gt;    M       16     16    25
#&gt;    NA       0      0     0
#&gt;
#&gt; $output.list$TABLES.COMBINED_all.sources_proportions
#&gt; M$sex
#&gt;    F    M   NA
#&gt; 0.43 0.57 0.00
#&gt;
#&gt; $output.list$TABLES.COMBINED_all.sources_counts
#&gt; M$sex
#&gt;  F  M NA
#&gt; 43 57  0
#&gt;
#&gt;
#&gt; $validity.message
#&gt; [1] "Data in all studies were valid"</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.table</span>(<span class="st">"M$hypertension"</span>,   <span class="at">datasources =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; $output.list
#&gt; $output.list$TABLE_rvar.by.study_row.props
#&gt;               study
#&gt; M$hypertension   nairobi    douala     dakar
#&gt;             0  0.3617021 0.2340426 0.4042553
#&gt;             1  0.3396226 0.2641509 0.3962264
#&gt;             NA       NaN       NaN       NaN
#&gt;
#&gt; $output.list$TABLE_rvar.by.study_col.props
#&gt;               study
#&gt; M$hypertension   nairobi douala dakar
#&gt;             0  0.4857143   0.44 0.475
#&gt;             1  0.5142857   0.56 0.525
#&gt;             NA 0.0000000   0.00 0.000
#&gt;
#&gt; $output.list$TABLE_rvar.by.study_counts
#&gt;               study
#&gt; M$hypertension nairobi douala dakar
#&gt;             0       17     11    19
#&gt;             1       18     14    21
#&gt;             NA       0      0     0
#&gt;
#&gt; $output.list$TABLES.COMBINED_all.sources_proportions
#&gt; M$hypertension
#&gt;    0    1   NA
#&gt; 0.47 0.53 0.00
#&gt;
#&gt; $output.list$TABLES.COMBINED_all.sources_counts
#&gt; M$hypertension
#&gt;  0  1 NA
#&gt; 47 53  0
#&gt;
#&gt;
#&gt; $validity.message
#&gt; [1] "Data in all studies were valid"</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.table</span>(<span class="st">"M$hyperlipidemia"</span>, <span class="at">datasources =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; $output.list
#&gt; $output.list$TABLE_rvar.by.study_row.props
#&gt;                 study
#&gt; M$hyperlipidemia   nairobi    douala     dakar
#&gt;               0  0.3773585 0.2452830 0.3773585
#&gt;               1  0.3191489 0.2553191 0.4255319
#&gt;               NA       NaN       NaN       NaN
#&gt;
#&gt; $output.list$TABLE_rvar.by.study_col.props
#&gt;                 study
#&gt; M$hyperlipidemia   nairobi douala dakar
#&gt;               0  0.5714286   0.52   0.5
#&gt;               1  0.4285714   0.48   0.5
#&gt;               NA 0.0000000   0.00   0.0
#&gt;
#&gt; $output.list$TABLE_rvar.by.study_counts
#&gt;                 study
#&gt; M$hyperlipidemia nairobi douala dakar
#&gt;               0       20     13    20
#&gt;               1       15     12    20
#&gt;               NA       0      0     0
#&gt;
#&gt; $output.list$TABLES.COMBINED_all.sources_proportions
#&gt; M$hyperlipidemia
#&gt;    0    1   NA
#&gt; 0.53 0.47 0.00
#&gt;
#&gt; $output.list$TABLES.COMBINED_all.sources_counts
#&gt; M$hyperlipidemia
#&gt;  0  1 NA
#&gt; 53 47  0
#&gt;
#&gt;
#&gt; $validity.message
#&gt; [1] "Data in all studies were valid"</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span><code>binary</code> vs <code>count</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>format = "binary"</code> is <em>does this patient have it at all?</em> (0/1). <code>format = "count"</code> is <em>how many records?</em> — here <code>n_visits</code> is right-skewed (most patients few visits, a handful many).</p>
</div>
</div>
</section>
<section id="one-recipe-several-tables" class="level2">
<h2 data-anchor-id="one-recipe-several-tables">7.3 One recipe, several tables</h2>
<p>A recipe can declare <strong>several outputs</strong>, each selecting a <strong>different subset of variables</strong>, so one extraction produces several purpose-built tables (e.g.&nbsp;a demographics table and a clinical one) — list them with <code>outputs = list(...)</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>rec_multi <span class="ot">&lt;-</span> <span class="fu">omop_recipe</span>(</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="fu">list</span>(</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">omop_variable</span>(<span class="at">table =</span> <span class="st">"person"</span>, <span class="at">column =</span> <span class="st">"gender_concept_id"</span>, <span class="at">format =</span> <span class="st">"sex_mf"</span>, <span class="at">name =</span> <span class="st">"sex"</span>),</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">omop_variable_age</span>(<span class="at">name =</span> <span class="st">"age"</span>, <span class="at">year =</span> <span class="dv">2024</span>),</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">omop_variable</span>(<span class="at">table =</span> <span class="st">"measurement"</span>, <span class="at">concept_id =</span> <span class="dv">3027018</span>, <span class="at">format =</span> <span class="st">"mean"</span>, <span class="at">name =</span> <span class="st">"heart_rate"</span>),</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">omop_variable</span>(<span class="at">table =</span> <span class="st">"condition_occurrence"</span>, <span class="at">concept_id =</span> <span class="dv">320128</span>, <span class="at">format =</span> <span class="st">"binary"</span>, <span class="at">name =</span> <span class="st">"hypertension"</span>)</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">outputs =</span> <span class="fu">list</span>(</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">omop_output</span>(<span class="at">name =</span> <span class="st">"demographics"</span>, <span class="at">variables =</span> <span class="fu">c</span>(<span class="st">"sex"</span>, <span class="st">"age"</span>), <span class="at">type =</span> <span class="st">"wide"</span>),</span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">omop_output</span>(<span class="at">name =</span> <span class="st">"clinical"</span>,     <span class="at">variables =</span> <span class="fu">c</span>(<span class="st">"heart_rate"</span>, <span class="st">"hypertension"</span>), <span class="at">type =</span> <span class="st">"wide"</span>)</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a><span class="fu">recipe_execute</span>(rec_multi, <span class="at">out =</span> <span class="fu">c</span>(<span class="at">demographics =</span> <span class="st">"DEMO"</span>, <span class="at">clinical =</span> <span class="st">"CLIN"</span>),</span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>               <span class="at">symbol =</span> <span class="st">"omop"</span>, <span class="at">conns =</span> conns)</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.colnames</span>(<span class="st">"DEMO"</span>, <span class="at">datasources =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; $nairobi
#&gt; [1] "person_id" "sex"       "age"
#&gt;
#&gt; $douala
#&gt; [1] "person_id" "sex"       "age"
#&gt;
#&gt; $dakar
#&gt; [1] "person_id" "sex"       "age"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.colnames</span>(<span class="st">"CLIN"</span>, <span class="at">datasources =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; $nairobi
#&gt; [1] "person_id"    "heart_rate"   "hypertension"
#&gt;
#&gt; $douala
#&gt; [1] "person_id"    "heart_rate"   "hypertension"
#&gt;
#&gt; $dakar
#&gt; [1] "person_id"    "heart_rate"   "hypertension"</code></pre>
</div>
</div>
</section>
</section>
<section id="filtering-at-extraction" class="level1">
<h1>8. Filtering at extraction</h1>
<p>Often you only want a <strong>subpopulation</strong>. Add a <code>filters</code> element so the servers only build the rows you ask for. Filters can only ever <strong>shrink</strong> a population, so they are safe. Here: <strong>patients aged 50+ who have hyperlipidemia</strong>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>rec_sub <span class="ot">&lt;-</span> <span class="fu">omop_recipe</span>(</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="fu">list</span>(</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">omop_variable</span>(<span class="at">table =</span> <span class="st">"person"</span>, <span class="at">column =</span> <span class="st">"gender_concept_id"</span>, <span class="at">format =</span> <span class="st">"sex_mf"</span>, <span class="at">name =</span> <span class="st">"sex"</span>),</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">omop_variable_age</span>(<span class="at">name =</span> <span class="st">"age"</span>, <span class="at">year =</span> <span class="dv">2024</span>)</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">filters =</span> <span class="fu">list</span>(</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">older       =</span> <span class="fu">omop_filter_age</span>(<span class="at">min =</span> <span class="dv">50</span>, <span class="at">year =</span> <span class="dv">2024</span>),</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">with_lipids =</span> <span class="fu">omop_filter_has_concept</span>(<span class="at">concept_id =</span> <span class="dv">432867</span>, <span class="at">table =</span> <span class="st">"condition_occurrence"</span>)</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">output =</span> <span class="fu">omop_output</span>(<span class="at">name =</span> <span class="st">"study"</span>, <span class="at">type =</span> <span class="st">"wide"</span>)</span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a><span class="fu">recipe_execute</span>(rec_sub, <span class="at">out =</span> <span class="fu">c</span>(<span class="at">study =</span> <span class="st">"SUB"</span>), <span class="at">symbol =</span> <span class="st">"omop"</span>, <span class="at">conns =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The cohort is smaller, and the minimum age respects the 50+ floor:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.dim</span>(<span class="st">"SUB"</span>, <span class="at">datasources =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; $`dimensions of SUB in nairobi`
#&gt; [1] 14  3
#&gt;
#&gt; $`dimensions of SUB in douala`
#&gt; [1] 11  3
#&gt;
#&gt; $`dimensions of SUB in dakar`
#&gt; [1] 19  3
#&gt;
#&gt; $`dimensions of SUB in combined studies`
#&gt; [1] 44  3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.summary</span>(<span class="st">"SUB$age"</span>, <span class="at">datasources =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; $nairobi
#&gt; $nairobi$class
#&gt; [1] "integer"
#&gt;
#&gt; $nairobi$length
#&gt; [1] 14
#&gt;
#&gt; $nairobi$`quantiles &amp; mean`
#&gt;       5%      10%      25%      50%      75%      90%      95%     Mean
#&gt; 54.55000 57.30000 60.75000 75.00000 84.50000 87.40000 89.75000 72.64286
#&gt;
#&gt;
#&gt; $douala
#&gt; $douala$class
#&gt; [1] "integer"
#&gt;
#&gt; $douala$length
#&gt; [1] 11
#&gt;
#&gt; $douala$`quantiles &amp; mean`
#&gt;       5%      10%      25%      50%      75%      90%      95%     Mean
#&gt; 61.00000 64.00000 64.50000 69.00000 81.50000 86.00000 86.50000 72.36364
#&gt;
#&gt;
#&gt; $dakar
#&gt; $dakar$class
#&gt; [1] "integer"
#&gt;
#&gt; $dakar$length
#&gt; [1] 19
#&gt;
#&gt; $dakar$`quantiles &amp; mean`
#&gt;       5%      10%      25%      50%      75%      90%      95%     Mean
#&gt; 59.90000 62.40000 66.00000 70.00000 81.50000 88.20000 89.20000 73.68421</code></pre>
</div>
</div>
<section id="combine-criteria-and-or-and-nesting" class="level2">
<h2 data-anchor-id="combine-criteria-and-or-and-nesting">Combine criteria — AND, OR, and nesting</h2>
<p>Listing several filters combines them with <strong>AND</strong>. For <strong>OR</strong> (or any nested logic) wrap them in <code>omop_filter_group()</code>. Here, patients who have <strong>hypertension OR hyperlipidemia</strong> — a <em>union</em>, so this cohort is larger than either diagnosis on its own:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>rec_or <span class="ot">&lt;-</span> <span class="fu">omop_recipe</span>(</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">variables =</span> <span class="fu">list</span>(</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">omop_variable</span>(<span class="at">table =</span> <span class="st">"person"</span>, <span class="at">column =</span> <span class="st">"gender_concept_id"</span>, <span class="at">format =</span> <span class="st">"sex_mf"</span>, <span class="at">name =</span> <span class="st">"sex"</span>),</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">omop_variable_age</span>(<span class="at">name =</span> <span class="st">"age"</span>, <span class="at">year =</span> <span class="dv">2024</span>)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">filters =</span> <span class="fu">list</span>(</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">cardiometabolic =</span> <span class="fu">omop_filter_group</span>(</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a>      <span class="fu">omop_filter_has_concept</span>(<span class="at">concept_id =</span> <span class="dv">320128</span>, <span class="at">table =</span> <span class="st">"condition_occurrence"</span>),  <span class="co"># hypertension</span></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">omop_filter_has_concept</span>(<span class="at">concept_id =</span> <span class="dv">432867</span>, <span class="at">table =</span> <span class="st">"condition_occurrence"</span>),  <span class="co"># hyperlipidemia</span></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">operator =</span> <span class="st">"OR"</span></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">output =</span> <span class="fu">omop_output</span>(<span class="at">name =</span> <span class="st">"study"</span>, <span class="at">type =</span> <span class="st">"wide"</span>)</span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb56-15"><a href="#cb56-15" aria-hidden="true" tabindex="-1"></a><span class="fu">recipe_execute</span>(rec_or, <span class="at">out =</span> <span class="fu">c</span>(<span class="at">study =</span> <span class="st">"ORC"</span>), <span class="at">symbol =</span> <span class="st">"omop"</span>, <span class="at">conns =</span> conns)</span>
<span id="cb56-16"><a href="#cb56-16" aria-hidden="true" tabindex="-1"></a><span class="fu">ds.dim</span>(<span class="st">"ORC"</span>, <span class="at">datasources =</span> conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt; $`dimensions of ORC in nairobi`
#&gt; [1] 23  3
#&gt;
#&gt; $`dimensions of ORC in douala`
#&gt; [1] 19  3
#&gt;
#&gt; $`dimensions of ORC in dakar`
#&gt; [1] 28  3
#&gt;
#&gt; $`dimensions of ORC in combined studies`
#&gt; [1] 70  3</code></pre>
</div>
</div>
<p>Switch <code>operator = "OR"</code> to <code>"AND"</code>, or nest <code>omop_filter_group()</code>s inside each other, to express any combination.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Filtering is a whole query language
</div>
</div>
<div class="callout-body-container callout-body">
<p>These cover the OMOP model, and every one only ever <strong>shrinks</strong> the population (so all are disclosure-safe):</p>
<ul>
<li><strong>Person:</strong> <code>omop_filter_sex()</code>, <code>omop_filter_age()</code>, <code>omop_filter_age_group()</code></li>
<li><strong>Diagnoses / drugs:</strong> <code>omop_filter_has_concept()</code>, <code>omop_filter_not_has_concept()</code>, <code>omop_filter_concept_count()</code></li>
<li><strong>Measurements:</strong> <code>omop_filter_has_measurement()</code>, <code>omop_filter_missing_measurement()</code>, <code>omop_filter_value()</code> (numeric threshold), <code>omop_filter_value_concept()</code></li>
<li><strong>Time &amp; utilisation:</strong> <code>omop_filter_date_range()</code>, <code>omop_filter_visit_count()</code>, <code>omop_filter_prior_observation()</code>, <code>omop_filter_followup()</code></li>
<li><strong>Combine:</strong> <code>omop_filter_group(..., operator = "AND" | "OR")</code>, nested to any depth</li>
</ul>
</div>
</div>
</section>
</section>
<section id="a-real-model-what-predicts-a-diagnosis" class="level1">
<h1>9. A real model: what predicts a diagnosis?</h1>
<p>A logistic regression of <strong>hyperlipidemia</strong> on age and sex, fitted jointly across the three hospitals. We show the raw <code>ds.glm</code> coefficients (<code>P_OR</code> is the odds ratio, with its 95% CI in the <code>*.P_OR</code> columns):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>fit1 <span class="ot">&lt;-</span> <span class="fu">ds.glm</span>(<span class="at">formula =</span> <span class="st">"M$hyperlipidemia ~ M$age + M$sex"</span>,</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">datasources =</span> conns)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>fit1<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;                Estimate Std. Error     z-value      p-value low0.95CI.LP high0.95CI.LP       P_OR low0.95CI.P_OR high0.95CI.P_OR
#&gt; (Intercept) -4.59371247 1.15761941 -3.96824071 7.240518e-05   -6.8626048    -2.3248201 0.01001394    0.001045092      0.08908812
#&gt; M$age        0.07020260 0.01719118  4.08364005 4.433569e-05    0.0365085     0.1038967 1.07272550    1.037183125      1.10948584
#&gt; M$sexM      -0.01449884 0.45779165 -0.03167126 9.747342e-01   -0.9117540     0.8827563 0.98560576    0.401818820      2.41755406</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Reading it
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>age</strong> is a clear, <strong>significant</strong> predictor (<code>P_OR</code> &gt; 1, tiny <code>p-value</code>); <strong>sex</strong> is not (<code>P_OR</code> ≈ 1). One clear effect, one null — produced without touching a patient record.</p>
</div>
</div>
<p>A <strong>multivariable</strong> model — hypertension on age, sex and hyperlipidemia:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>fit2 <span class="ot">&lt;-</span> <span class="fu">ds.glm</span>(<span class="at">formula =</span> <span class="st">"M$hypertension ~ M$age + M$sex + M$hyperlipidemia"</span>,</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">datasources =</span> conns)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>fit2<span class="sc">$</span>coefficients</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#&gt;                     Estimate Std. Error    z-value     p-value low0.95CI.LP high0.95CI.LP      P_OR low0.95CI.P_OR high0.95CI.P_OR
#&gt; (Intercept)      -2.38653694 0.97654087 -2.4438680 0.014530743  -4.30052187   -0.47255201 0.0842051     0.01338003       0.3840124
#&gt; M$age             0.04583409 0.01630956  2.8102598 0.004950153   0.01386795    0.07780024 1.0469007     1.01396455       1.0809067
#&gt; M$sexM           -0.87002367 0.45075104 -1.9301645 0.053586456  -1.75347948    0.01343214 0.4189416     0.17317035       1.0135228
#&gt; M$hyperlipidemia  0.28922601 0.47408107  0.6100771 0.541810727  -0.63995581    1.21840783 1.3353935     0.52731572       3.3817991</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Age stays significant; sex is borderline; the comorbidity adjustment is not significant. On ~100 patients power is limited — the larger <strong>GiBleed</strong> study (next) delivers a strongly significant result.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>DSI<span class="sc">::</span><span class="fu">datashield.logout</span>(conns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="where-to-go-next" class="level1">
<h1>Where to go next</h1>
<p>You have the full toolkit: <strong>connect → explore → recipe (variables / format / filters / output, single or multiple) → execute → ratify → summarise → model</strong>. Next: the <strong><a href="omop-exercises.html">exercise sheet</a></strong>, then the larger <strong><a href="gibleed.html">GiBleed study</a></strong>.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button,
          { trigger: "manual",
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/isglobal-brge\.github\.io\/workshop_DSWB");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config);
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined;
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              }
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            }
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>
    <div class="nav-footer-center">
<p>© 2025 <a href="https://www.isglobal.org">ISGlobal - Barcelona Institute for Global Health</a><br> <a href="https://brge.isglobal.org">Bioinformatics Research Group in Epidemiology (BRGE)</a></p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>
<script src="workshop-interactive.js"></script>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>